version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  nginx:
    container_name: nginx-server
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - node

  node: #name of the second service
    build: . # specify the directory of the Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8083:8083" #specify ports forewarding
    links:
      - database # link this service to the database service
    depends_on:
      - database  

  database: # name of the third service
    image: mongo # specify image to build container from
    volumes:
      - /app/server/config.js
    # ports:
    #   - "27017:27017" # specify port forewarding